-- Add 10 short blog posts
INSERT INTO public.blog_articles (title, excerpt, category, author, date, read_time, image, featured, content) VALUES
('Quick Tips for New Gamers', 'Essential advice for anyone starting out with online gaming.', 'Tips', 'Sarah Johnson', 'February 12, 2026', '2 min read', '/blog/placeholder7.jpg', false, '<p>Start with small limits, take breaks, and never chase losses.</p>'),
('Understanding Odds', 'A brief intro to how odds work in gaming.', 'Education', 'Michael Chen', 'February 11, 2026', '2 min read', '/blog/placeholder8.jpg', false, '<p>Odds represent probability. The house always has an edge—play for fun, not profit.</p>'),
('When to Take a Break', 'Signs you need to step away from gaming.', 'Tips', 'Emma Williams', 'February 9, 2026', '2 min read', '/blog/placeholder9.jpg', false, '<p>If you''re tired, stressed, or losing focus, it''s time for a break.</p>'),
('Budgeting for Entertainment', 'How to allocate gaming in your monthly budget.', 'Education', 'Dr. Robert Martinez', 'February 7, 2026', '3 min read', '/blog/placeholder10.jpg', false, '<p>Treat gaming like any other entertainment expense. Set a limit and stick to it.</p>'),
('Mobile Gaming Safety', 'Stay safe when gaming on your phone.', 'Safety', 'Alex Thompson', 'February 6, 2026', '2 min read', '/blog/placeholder11.jpg', false, '<p>Use strong passwords, enable 2FA, and avoid public Wi‑Fi for sensitive actions.</p>'),
('Talking to Kids About Gaming', 'How to discuss responsible gaming with children.', 'Support', 'Lisa Anderson', 'February 4, 2026', '3 min read', '/blog/placeholder12.jpg', false, '<p>Be open, set clear rules, and lead by example with your own habits.</p>'),
('Cooling-Off Periods', 'What they are and when to use them.', 'Tips', 'Sarah Johnson', 'February 2, 2026', '2 min read', '/blog/placeholder13.jpg', false, '<p>A cooling-off period lets you step back for 24 hours or more. Use it when you need space.</p>'),
('Reality Check Reminders', 'How reminder tools help you stay aware.', 'Technology', 'Michael Chen', 'February 1, 2026', '2 min read', '/blog/placeholder14.jpg', false, '<p>Reality checks show time and spend. They help you stay in control.</p>'),
('Recognizing a Slip', 'What to do when you exceed your limits.', 'Support', 'Emma Williams', 'January 31, 2026', '2 min read', '/blog/placeholder15.jpg', false, '<p>One slip doesn''t mean failure. Acknowledge it, adjust your limits if needed, and move forward.</p>'),
('Where to Get Help', 'Resources for problem gaming support.', 'Support', 'Dr. Robert Martinez', 'January 29, 2026', '2 min read', '/blog/placeholder16.jpg', false, '<p>Helplines, support groups, and counselors are available. Reach out when you need them.</p>');
